### ISSUE TITLE
希望大大在ok_data_level3、ok_data_level4中：加入geo字段方便定位解析出城市、加入拼音速记码方便拼音前缀搜索

### ISSUE THREAD

**Issue by iMaxSys** [xiangyuecn/AreaCity-JsSpider-StatsGov#10]
希望大大在ok_data_level3、ok_data_level4中加入geo字段，很多人的系统其实只是需要定位在那个城市，geo足够了，而且快速搜索的话，简拼/速记码较为方便，比如：bj=北京，sh=上海，希望大大考虑，感谢你的辛勤劳动和付出。

**Comment by xiangyuecn** [comment]
哈哈，谢谢支持。

1. geo字段确实不算大，大的是polygon字段；但仅仅通过geo这个中心坐标是没法定位到城市的，因为没法通过一点来确定另一个点是否在一个边界范围内；因此必须提供城市的polygon边界才能判定一个坐标是否在一个城市内，从而解析出坐标所在城市。

2. 简拼(jp)这种可以使用pinyin字段来进行处理，这个字段已经是name的全屏，搜索前把pinyin分解一下（代码量最多也就十来行就能搞定）；就能达到你要的这种效果。

ps：目前库里面的pinyin_prefix的主要作用是用来做排序的，参考README里面有段《排序方案》的章节专门介绍的这个字段和演变历史。

**Comment by iMaxSys** [comment]
感谢作者的劳动和付出，加油
