### ISSUE TITLE
苏州工业园区不是民政部划分的县级行政区

### ISSUE THREAD

**Issue by amorphobia** [xiangyuecn/AreaCity-JsSpider-StatsGov#15]
在民政部的县级以上行政区划代码中，没有苏州工业园区
http://www.mca.gov.cn//article/sj/xzqh/2020/2020/2020092500801.html

据网友考证，苏州工业园区在拥有单独统计代码之前，使用的是姑苏区的代码，并且在民政部的区划中也是属于姑苏区的
https://ichon.me/post/1034.html

**Comment by xiangyuecn** [comment]
嗯，这个是特殊处理的数据

https://github.com/xiangyuecn/AreaCity-JsSpider-StatsGov/blob/1e3705a08ed15d27cc8dc41605770d6c4db80837/src/1_5_%E5%90%88%E5%B9%B6.js#L37-L45

**Comment by amorphobia** [comment]
请问这个意思是说，这是特意将工业园区划分出来的吗？那么请问划分的标准就是与统计局一样吧？

我个人的意见是，工业园区没有人大和政协，只是经济上的一个“园区”、“新区”，不是一个真正意义上的行政区，如果从实用意义上来讲，将他们分开是更好的选择，那么我建议可以在数据的注释和说明介绍的地方注明一下这个特殊情况，让用户知道从行政区划意义上看，工业园区是姑苏区的一部分。

**Comment by xiangyuecn** [comment]
嗯，整个数据里面就这一个工业园区是特殊的，其他地方的园区什么的都是没有的。

下次更新的时候，我在文档里面特别注释一下。

**Comment by xiangyuecn** [comment]
已注释 https://github.com/xiangyuecn/AreaCity-JsSpider-StatsGov/commit/c58c20e207bef1523c528512c99875be95e0112d

**Comment by xiangyuecn** [comment]
https://github.com/xiangyuecn/AreaCity-JsSpider-StatsGov/commit/c84ea2471bd4dc44ffd64e40195bb4c6bf49c4c1 版本已移除苏州工业园区
