### ISSUE TITLE
独特的地名专用的多音字，乐亭的乐读lào

### ISSUE THREAD

**Issue by hye** [xiangyuecn/AreaCity-JsSpider-StatsGov#2]
REF：《现代汉语词典》 第6版以后， [乐亭官网](http://www.laoting.gov.cn/)
本来说PR 改[ok_data_level3.csv](https://github.com/xiangyuecn/AreaCity-JsSpider-StatsGov/blob/master/2019/%E9%87%87%E9%9B%86%E5%88%B0%E7%9A%84%E6%95%B0%E6%8D%AE/ok_data_level3.csv) 的，
可是level4 txt可能都有，没改全就把PR关了

**Comment by xiangyuecn** [comment]
看到了，人工调整一下，晚会发布新版本

**Comment by xiangyuecn** [comment]
新版本已发布，`乐亭县`下面的`乐亭`全部改过来了，是有好几处。另外 `乐亭县` 下面有个`乐安街道`，根据上下语境，我也改成了`lao`

**Comment by hye** [comment]
> 新版本已发布，`乐亭县`下面的`乐亭`全部改过来了，是有好几处。另外 `乐亭县` 下面有个`乐安街道`，根据上下语境，我也改成了`lao`

后面这个我就不确定了 🤷‍♂️
