### ISSUE TITLE
为什么数据里有很多非行政区域的数据？

### ISSUE THREAD

**Issue by JoeZing** [xiangyuecn/AreaCity-JsSpider-StatsGov#24]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/5292292/163779673-33bf6622-95bd-4438-ba8b-5706e04b489b.png">

<img width="419" alt="image" src="https://user-images.githubusercontent.com/5292292/163779939-427781c8-df75-4114-a03b-6852d2c13b22.png">

**Comment by xiangyuecn** [comment]
乡镇级的区划数据大部分是来自腾讯地图的接口，原封不动。乡镇数据太多了，名字长度超过6个字的有将近1000个，不排除里面有错的，但一个个核实就像大海捞针，太难了，所以直接用的腾讯原封不动的数据；还是因为数据量太大，这些出错的占比就很小了

毕竟这种数据都是需要维护的东西，就像京东淘宝他们，也都是没有100%实时准确的，也是需要有反馈+更新，很多时候这些瑕疵并不会对使用产生过大影响

**Comment by zhouxiaofu** [comment]
正常数据，淘宝收货地址也是这样的

**Comment by JoeZing** [comment]
Thx

**Comment by JoeZing** [comment]
Thx
