### ISSUE TITLE
能抓取到excel么，csv好像数据会错乱

### ISSUE THREAD

**Issue by liyang-live** [xiangyuecn/AreaCity-JsSpider-StatsGov#3]
能抓取到excel么，csv好像数据会错乱，

**Comment by xiangyuecn** [comment]
用wps打开试试看，感觉csv格式比execl的格式稳定的多，因为语法简单+纯文本，编码是utf-8 带 bom头。

我把省市区镇4级接近4.7万数据导入SQL Server没有格式上的问题。
