### ISSUE TITLE
能否转为gis常用的geojson 或shp文件？

### ISSUE THREAD

**Issue by Inblac** [xiangyuecn/AreaCity-JsSpider-StatsGov#4]
提一个伸手党的问题，只因自己尝试后没有搞定。
能否将ok_geo.csv 转为shp或geojson提供下载；或者有没有大佬提供一个可行的思路``

**Comment by xiangyuecn** [comment]
> 除了ok_geo.csv文件比较大之外，应该不存在什么格式转换难题。前提条件是对目标格式的具体语法非常了解。

可以先把csv转换成你所用语言好处理的中间格式，比如json，再去转换成目标格式。

1. 转换成中间格式，可以参考`测试和WEB数据格式转换工具.js`中对csv转成js对象的代码（适用于ok_geo）：
https://github.com/xiangyuecn/AreaCity-JsSpider-StatsGov/blob/ba2ece408fc9c8ca4249e07ef85994005da7e0cc/%E6%B5%8B%E8%AF%95%E5%92%8CWEB%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F%E8%BD%AC%E6%8D%A2%E5%B7%A5%E5%85%B7.js#L444-L467
2. 转换成目标格式，比如：`geojson` 或`shp`格式，中间格式好处理的数据已经有了，根据目标格式的具体语法把数据填充过去就ok啦。

由于不知道`geojson` 或`shp`格式的具体语法，第二步需要自己去摸索。`geojson`格式应该比较简单，`shp`二进制格式就难说了。

-----

要是确实搞不定，还有一个简单方法，可以参考：
https://github.com/xiangyuecn/AreaCity-JsSpider-StatsGov/blob/ba2ece408fc9c8ca4249e07ef85994005da7e0cc/2019/%E5%9D%90%E6%A0%87%E5%92%8C%E8%BE%B9%E7%95%8C/map_geo_%E6%A0%BC%E5%BC%8F%E5%8C%96.js#L41-L48

直接把ok_geo.csv数据导入数据库，用sql将坐标文本转换成空间数据，然后再尝试数据库里面转换成需要的格式。

**Comment by Inblac** [comment]
谢谢，我尝试看看。
