### ISSUE TITLE
Some 县s are missing

### ISSUE THREAD

**Issue by ztzthu** [xiangyuecn/AreaCity-JsSpider-StatsGov#5]
Sorry for using English... I currently cannot type Chinese on my laptop
Some of the 县s are missing. The missing items include:
新疆维吾尔自治区 昆玉市
新疆维吾尔自治区 五家渠市
新疆维吾尔自治区 可克达拉市
新疆维吾尔自治区 双河市
青海省 海西蒙古族藏族自治州 大柴旦行政委员会 (which is called "海西蒙古族藏族自治州 海西蒙古族藏族自治州直辖" in Amap)
It would be great if you could add these missing items. Thank you!

**Comment by xiangyuecn** [comment]
问题 | 数据 | 解释
| :-: | :-: | :- |
青海省 海西蒙古族藏族自治州 大柴旦行政委员会| 青海 海西 大柴旦行政委员会 | (蒙古族)(藏族)(自治州)这几个字在精简名称时已被清除
新疆维吾尔自治区 4个直辖市| 新疆 直辖市 * |  统计局只有五家渠，剩下3个并未包含在数据里面，但民政部数据里面包含剩下的3个

是我只采用了统计局的数据导致的数据不足的问题；**有时间** 我看看把民政部那部分数据合并过来就能减轻这个问题，整个数据都要更新。

**Comment by xiangyuecn** [comment]
已补全 民政部 的新疆数据，新版本2018.190621已发布🎈

**Comment by xiangyuecn** [comment]
https://github.com/modood/Administrative-divisions-of-China/issues/53
