### ISSUE TITLE
求助大佬

### ISSUE THREAD

**Issue by hegaojian** [xiangyuecn/AreaCity-JsSpider-StatsGov#7]
大佬，我想生成一个 带有全字段的json导出为JSON对象
id,pid,deep,name,pinyin_prefix,pinyin,ext_id,ext_name

我把UserFormat修改了好像不起效果（其实修改的对不对自己心里也没谱，菜鸡看不太懂js代码）
大佬你能帮我修改一下UserFormat吗

**Comment by xiangyuecn** [comment]
可以，把需要的格式样本发一下我看看

**Comment by xiangyuecn** [comment]
在线编辑UserFormat的源码已经修改过了，现在应该更方便使用了，先自己看看能不能调成你要的格式

**Comment by hegaojian** [comment]
可以了，万分感谢大佬！:smile::smile::smile:
